#!/usr/bin/env python

import sys
import getopt


MB = 1024*1024
MW = int(8e6)

def MW2MB(mw):
    return mw * MW / MB

def MB2MW(mb):
    return mb * MB / MW

def GB2MW(gb):
    return MB2MW(gb*1024)


if __name__ == '__main__':

    usage = """
usage: memconverter.py [options] <memory> <memory format> <destination format>

For example converting 200gigabyte to megawords is
memconverter.py 200 gb mw

optional arguments:

   -h, --help       shows this help message and exit
   -b, --bit        change the bit size, either 32 or 64 (default)
"""

    args = sys.argv[1:]


    for i in range(len(args)):

        if args[i] in ('-h', '--help'):
            print usage
            quit()

        if args[i] in ('-b', '--bit'):
            bit = args[i+1]
            del args[i]
            del args[i+1]
            break


    if len(args) < 3:
        print usage
        quit()


    memory_value = int(args[0])
    memory_format = args[1]
    destination_formation = args[2]

    # words to bytes
    if memory_format[-1] == 'w':

        print MW2GB(memory_value), 'gigabyte'

    # bytes to words
    elif memory_format[-1] == 'b':

        print GB2MW(memory_value), 'megawords'

    else:
        print "error in formats"
        print usage
        quit()

